# Generated by Django 5.0.6 on 2024-06-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogoRemoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=250)),
                ("url_listado_raiz", models.URLField()),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CatalogoRemotoConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=250)),
                (
                    "url_script_sitio",
                    models.URLField(help_text="https://teresita.com.mx/cmd.php?"),
                ),
                (
                    "comando_listar",
                    models.TextField(help_text="&cmd=ls&", max_length=250),
                ),
                (
                    "comando_mostrar",
                    models.TextField(help_text="&cmd=show&", max_length=250),
                ),
                (
                    "raiz_de_listado",
                    models.TextField(
                        help_text="&root=sie/Docu/Masters%20MP&", max_length=250
                    ),
                ),
                (
                    "ruta_movil_de_archivo",
                    models.TextField(
                        help_text="&endpoint=ACE/ACE01/ACE01-005.png", max_length=250
                    ),
                ),
                (
                    "elemento_thumbnail",
                    models.TextField(
                        help_text="&thumbnail=true&width=50", max_length=250
                    ),
                ),
                ("elementos_por_fila", models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                "ordering": ["nombre"],
                "permissions": [
                    ("synchronize_remote_catalogs", "Sincronizar catalogos remotos")
                ],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=250)),
                ("mimetype", models.TextField(max_length=100)),
                ("url", models.URLField()),
                ("url_thumbnail", models.URLField()),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_catalogo_remoto.catalogoremoto",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
