# Generated by Django 5.0.6 on 2024-06-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_catalogo_remoto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogoremoto",
            name="configuracion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogos",
                to="app_catalogo_remoto.catalogoremotoconfiguracion",
            ),
            preserve_default=False,
        ),
    ]
