# Generated by Django 5.0.6 on 2024-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_catalogo_remoto", "0002_catalogoremoto_configuracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="comando_listar",
            field=models.CharField(help_text="&cmd=ls&", max_length=250),
        ),
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="comando_mostrar",
            field=models.CharField(help_text="&cmd=show&", max_length=250),
        ),
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="elemento_thumbnail",
            field=models.CharField(
                help_text="&thumbnail=true&width=50", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="nombre",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="raiz_de_listado",
            field=models.CharField(
                help_text="&root=sie/Docu/Masters%20MP&", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="ruta_movil_de_archivo",
            field=models.CharField(
                help_text="&endpoint= -> &endpoint=ACE/ACE01/ACE01-005.png",
                max_length=250,
            ),
        ),
    ]
