# Generated by Django 5.0.6 on 2024-06-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_catalogo_remoto", "0005_alter_listacatalogoitem_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listacatalogoitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listas",
                to="app_catalogo_remoto.item",
            ),
        ),
    ]
