# Generated by Django 5.0.6 on 2024-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_catalogo_remoto", "0006_alter_listacatalogoitem_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listacatalogoitem",
            options={"ordering": ["lista__nombre", "item__nombre"]},
        ),
        migrations.RemoveField(
            model_name="listacatalogoitem",
            name="nombre",
        ),
    ]
