# Generated by Django 5.0.6 on 2024-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_catalogo_remoto", "0007_alter_listacatalogoitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogoremoto",
            name="url_listado_raiz",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="catalogoremotoconfiguracion",
            name="url_script_sitio",
            field=models.URLField(
                help_text="https://teresita.com.mx/cmd.php?", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="item",
            name="url_thumbnail",
            field=models.URLField(max_length=500),
        ),
    ]
