# Generated by Django 5.0.6 on 2024-06-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalogo_remoto', '0008_alter_catalogoremoto_url_listado_raiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoremoto',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
