# Generated by Django 3.0.7 on 2021-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_valuacion_puestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='exponente',
            field=models.DecimalField(decimal_places=5, default=2.1, max_digits=8),
        ),
    ]
