# Generated by Django 3.0.7 on 2021-04-20 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_valuacion_puestos', '0002_factor_exponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=8)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['parametro', 'fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='factor',
            name='exponente',
        ),
        migrations.AlterField(
            model_name='factor',
            name='ponderacion_nivel_1',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ponderación'),
        ),
        migrations.CreateModel(
            name='ParametroVPHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=8)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('raiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='app_valuacion_puestos.ParametroVP')),
            ],
            options={
                'ordering': ['raiz', '-fecha'],
            },
        ),
    ]
