# Generated by Django 3.0.7 on 2021-04-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_valuacion_puestos', '0003_auto_20210420_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabulador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabulador', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['tabulador'],
            },
        ),
        migrations.AlterModelOptions(
            name='parametrovphistoria',
            options={'ordering': ['raiz', '-fecha', '-pk']},
        ),
        migrations.CreateModel(
            name='TabuladorNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(default=1)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tabulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='app_valuacion_puestos.Tabulador')),
            ],
            options={
                'ordering': ['tabulador', 'posicion'],
                'unique_together': {('tabulador', 'posicion')},
            },
        ),
    ]
