# Generated by Django 3.0.7 on 2021-04-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_valuacion_puestos', '0005_puesto_tabulador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['posicion', 'puesto'], 'permissions': [('view_fp_puntos', 'Reporte Factores por Puesto - Puntos'), ('view_fp_niveles', 'Reporte Factores por Puesto - Niveles'), ('view_vp', 'Reporte Valor por Puesto'), ('view_gp', 'Grafica de Puestos')]},
        ),
    ]
