# Generated by Django 3.0.7 on 2021-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_valuacion_puestos', '0009_auto_20210428_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestoevaluacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
