# Generated by Django 3.0.7 on 2021-05-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_valuacion_puestos', '0010_auto_20210428_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['posicion', 'puesto'], 'permissions': [('view_fp_puntos', 'Reporte Factores por Puesto - Puntos'), ('view_fp_niveles', 'Reporte Factores por Puesto - Niveles'), ('view_vp', 'Reporte Valor por Puesto'), ('view_gp', 'Grafica de Puestos'), ('view_gp_pesos', 'Grafica de Puestos en pesos')]},
        ),
    ]
