# Generated by Django 5.0.6 on 2024-07-22 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': [('update_report', 'Actualizar Reporte')],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=250)),
                ('concepto', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('D', 'Detalle'), ('P', 'Promedio')], default='D', max_length=20)),
                ('periodo', models.DateField()),
                ('valor', models.IntegerField(default=0)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app_timeseries_report.reporte')),
            ],
        ),
    ]
