# Generated by Django 5.0.6 on 2024-07-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_timeseries_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['nombre'], 'permissions': [('update_report_by_hand', 'Actualizar Reporte Manual'), ('update_report_by_txt', 'Actualizar Reporte TXT'), ('update_report_by_xlsx', 'Actualizar Reporte XLSX')]},
        ),
    ]
