# Generated by Django 5.0.6 on 2024-08-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_timeseries_report', '0002_alter_reporte_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='RegistroTS',
        ),
        migrations.RenameModel(
            old_name='Reporte',
            new_name='ReporteTS',
        ),
    ]
