# Generated by Django 5.0.6 on 2024-08-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timeseries_report', '0003_rename_registro_registrots_rename_reporte_reportets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportets',
            name='concepto_predefinido',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
