# Generated by Django 5.0.6 on 2024-08-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_timeseries_report', '0004_reportets_concepto_predefinido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrots',
            options={'ordering': ['entidad', 'concepto', 'tipo', 'periodo']},
        ),
    ]
