# Generated by Django 3.0.7 on 2021-06-22 14:34

import app_tablero.estadistico_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('entidad', models.CharField(max_length=2)),
                ('cuenta', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=10)),
                ('pre_cve', models.CharField(max_length=30)),
                ('pre_posicion', models.PositiveSmallIntegerField(default=0)),
                ('pre_cve_2', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['cuenta', 'formato'],
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estadistico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(default=app_tablero.estadistico_models.get4month)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle', to='app_tablero.Cuenta')),
            ],
            options={
                'ordering': ['cuenta', '-periodo'],
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='app_tablero.Tablero'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('objeto', models.CharField(max_length=20)),
                ('objeto_tipo', models.CharField(max_length=20)),
                ('en_respuesta_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_tablero.Comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
    ]
