# Generated by Django 3.0.7 on 2021-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='nombre_de_archivo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
