# Generated by Django 3.0.7 on 2021-07-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablero', '0002_tablero_nombre_de_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='app_tablero.Tablero'),
        ),
        migrations.AlterField(
            model_name='estadistico',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app_tablero.Cuenta'),
        ),
    ]
