# Generated by Django 3.0.7 on 2021-07-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablero', '0003_auto_20210727_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticoAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(default=2021, verbose_name='Año')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_anual', to='app_tablero.Cuenta')),
            ],
            options={
                'ordering': ['cuenta', '-anio'],
            },
        ),
    ]
