# Generated by Django 3.0.7 on 2021-08-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablero', '0004_estadisticoanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='cuentas_base',
            field=models.CharField(default='', max_length=200),
        ),
    ]
