# Generated by Django 3.0.7 on 2021-08-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablero', '0005_tablero_cuentas_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticoanual',
            options={'ordering': ['cuenta', 'anio']},
        ),
        migrations.AddField(
            model_name='tablero',
            name='cuenta_ventas_netas',
            field=models.CharField(default='40000', max_length=10),
        ),
    ]
