# Generated by Django 3.0.7 on 2021-08-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablero', '0006_auto_20210803_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistico',
            options={'ordering': ['cuenta', 'periodo']},
        ),
    ]
