# Generated by Django 5.0.6 on 2024-05-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tablero", "0007_auto_20210810_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadisticoanual",
            name="anio",
            field=models.PositiveSmallIntegerField(default=2024, verbose_name="Año"),
        ),
    ]
