# Generated by Django 3.0.7 on 2021-03-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zend_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuopc',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
