# Generated by Django 3.0.7 on 2021-03-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zend_django', '0002_menuopc_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuopc',
            name='visible',
        ),
    ]
