# Generated by Django 3.0.7 on 2021-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zend_django', '0003_remove_menuopc_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosistema',
            name='tipo',
            field=models.CharField(choices=[('INTEGER', 'Entero'), ('STRING', 'Cadena'), ('TEXT', 'Texto Largo'), ('PICTURE', 'Imagen'), ('FILE', 'Archivo'), ('DECIMAL', 'Decimal')], default='STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='parametrousuario',
            name='tipo',
            field=models.CharField(choices=[('INTEGER', 'Entero'), ('STRING', 'Cadena'), ('TEXT', 'Texto Largo'), ('PICTURE', 'Imagen'), ('FILE', 'Archivo'), ('DECIMAL', 'Decimal')], default='STRING', max_length=20),
        ),
    ]
