# Generated by Django 3.0.4 on 2020-04-06 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['dimension', 'esfera', 'padre__dimension'],
            },
        ),
        migrations.CreateModel(
            name='Esfera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=100)),
                ('icono', models.ImageField(upload_to='esferas')),
            ],
            options={
                'ordering': ['sigla', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('single', 'Reporte Único')], default='daily', max_length=20)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('doublequote', models.BooleanField(default=True)),
                ('escapechar', models.CharField(blank=True, max_length=5)),
                ('lineterminator', models.CharField(default='\\n', max_length=5)),
                ('quotechar', models.CharField(default='"', max_length=5)),
                ('quoting', models.CharField(choices=[('1', 'QUOTE_ALL'), ('0', 'QUOTE_MINIMAL'), ('2', 'QUOTE_NONNUMERIC'), ('3', 'QUOTE_NONE')], default='0', max_length=20)),
                ('skipinitialspace', models.BooleanField(default=False)),
                ('strict', models.BooleanField(default=False)),
                ('primer_linea_con_encabezados', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='app_reports.DimensionReporte')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dimension', 'nombre'],
                'unique_together': {('dimension', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='dimensionreporte',
            name='esfera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='app_reports.Esfera'),
        ),
        migrations.AddField(
            model_name='dimensionreporte',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdimensiones', to='app_reports.DimensionReporte'),
        ),
        migrations.CreateModel(
            name='CampoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('posicion', models.SmallIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('DECIMAL', 'Decimal'), ('INTEGER', 'Entero'), ('STRING', 'Cadena')], default='INTEGER', max_length=20)),
                ('valor_default', models.CharField(blank=True, max_length=100)),
                ('mostrar', models.BooleanField(default=True)),
                ('es_llave', models.BooleanField(default=False)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='app_reports.Reporte')),
            ],
            options={
                'ordering': ['reporte__nombre', 'posicion', 'campo'],
            },
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INNER JOIN', 'INNER JOIN'), ('LEFT JOIN', 'LEFT JOIN'), ('RIGHT JOIN', 'RIGHT JOIN')], default='INNER JOIN', max_length=20)),
                ('campo_derecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_derecha', to='app_reports.CampoReporte')),
                ('campo_izquierda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_izquierda', to='app_reports.CampoReporte')),
            ],
            options={
                'ordering': ['campo_izquierda__reporte__nombre', 'campo_izquierda__campo', 'campo_derecha__reporte__nombre', 'campo_derecha__campo'],
                'unique_together': {('campo_izquierda', 'campo_derecha', 'tipo')},
            },
        ),
        migrations.AddConstraint(
            model_name='dimensionreporte',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('esfera__isnull', True), ('padre__isnull', False)), models.Q(('esfera__isnull', False), ('padre__isnull', True)), _connector='OR'), name='cstr_esfera_padre'),
        ),
        migrations.AlterUniqueTogether(
            name='camporeporte',
            unique_together={('reporte', 'posicion'), ('reporte', 'campo')},
        ),
    ]
